name: examples-counter-cli
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: Example Counter cli application for eventium
description: Example Counter cli application for eventium
stability: experimental
license: MIT

dependencies:
  - base >= 4.9 && < 5
  - eventium-core
  - eventium-memory

  - safe
  - stm

executables:
  counter-cli:
    main: counter-cli.hs
    ghc-options: -Wall
