name: eventium-memory
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: In-memory implementations for eventium
description: In-memory implementations for eventium
stability: experimental
category: Database,Eventsourcing
license: MIT
license-file: LICENSE.md

github: aleks-sidorenko/eventium

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - eventium-core

  - containers
  - mtl
  - safe
  - stm

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventium-test-helpers
    build-tools:
      - hspec-discover
