name: examples-cafe
version: "0.1.0"
maintainer: David Reaver, Alexander Sidorenko
synopsis: Example cafe application for eventful
description: Example cafe application for eventful
maintainer: David Reaver, Alexander Sidorenko
stability: experimental
license: MIT

dependencies:
  - base >= 4.9 && < 5
  - eventful-core
  - eventful-memory
  - eventful-sqlite

  - aeson
  - aeson-casing
  - aeson-pretty
  - ansi-terminal
  - bytestring
  - containers
  - lens
  - monad-logger
  - mtl
  - optparse-applicative
  - persistent
  - persistent-sqlite
  - persistent-template
  - safe
  - stm
  - text

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  cafe-main:
    main: cafe-main.hs
    ghc-options: -Wall
    source-dirs:
      - app
    dependencies:
      - examples-cafe

  cafe-chef-todo-main:
    main: cafe-chef-todo-main.hs
    ghc-options: -Wall
    source-dirs:
      - app
    dependencies:
      - examples-cafe
