name: eventium-sqlite
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: SQLite implementations for eventium
description: SQLite implementations for eventium
stability: experimental
category: Database,Eventsourcing,SQLite
license: MIT
license-file: LICENSE.md

github: aleks-sidorenko/eventium

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - eventium-core
  - eventium-sql-common

  - aeson
  - bytestring
  - mtl
  - persistent
  - text
  - uuid

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventium-test-helpers
      - persistent-sqlite
