name: eventium-dynamodb
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: Library for eventium DynamoDB event stores
description: Library for eventium DynamoDB event stores
stability: experimental
category: Database,Eventsourcing,AWS
license: MIT
license-file: LICENSE.md

github: aleks-sidorenko/eventium

dependencies:
  - base >= 4.9 && < 5
  - eventium-core

  - aeson
  - amazonka
  - amazonka-dynamodb
  - bytestring
  - conduit
  - lens
  - safe
  - text
  - unordered-containers
  - vector

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - QuickCheck
      - quickcheck-instances
      - eventium-test-helpers
